name: 'Uses Private'
description: ''
inputs:
  github-token:
    description: 'Token'
    required: true
  repository:
    description: 'Repository'
    required: true
  workspace:
    description: 'Repository'
    default: '..'
  command:
    description: 'Command'
    default: 'echo -n'
  
runs:
  using: 'composite'
  steps:
    - uses: framely/actions-composite-expand@main
      with:
        main: |-
          org_name=$(echo ${{ inputs.repository }}    | awk -F '/|@' '{print $1}')
          repo_name=$(echo ${{ inputs.repository }}   | awk -F '/|@' '{print $2}')
          branch_name=$(echo ${{ inputs.repository }} | awk -F '/|@' '{print $3}')

          mkdir -p ${{ inputs.workspace }} && cd ${{ inputs.workspace }} && \
          rm -rf ${repo_name} && \
          git clone --depth=1 -b ${branch_name} https://${{ inputs.github-token }}@github.com/${org_name}/${repo_name}
          cd ${repo_name}
          ${{ inputs.command }}

        post: |-
          org_name=$(echo ${{ inputs.repository }}    | awk -F '/|@' '{print $1}')
          repo_name=$(echo ${{ inputs.repository }}   | awk -F '/|@' '{print $2}')
          branch_name=$(echo ${{ inputs.repository }} | awk -F '/|@' '{print $3}')

          cd ${{ inputs.workspace }} && rm -rf ${repo_name}
